# Generated by Django 6.0.5 on 2026-05-15 18:50

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0169_tasktemplate_filtering_labels'),
        ('iam', '0021_fix_auditee_iam_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecoveryProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('procedure_type', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore'), ('failover', 'Failover'), ('hardening', 'Hardening'), ('monitoring', 'Monitoring')], default='backup', max_length=20, verbose_name='Procedure type')),
                ('content', models.TextField(blank=True, help_text='Procedure content (markdown)', null=True, verbose_name='Content')),
                ('version', models.CharField(blank=True, default='1.0', max_length=50, verbose_name='Version')),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='Last updated')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_procedures', to='core.asset', verbose_name='Asset')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_procedures', to='core.evidence', verbose_name='Evidence')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recovery_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Asset recovery procedure',
                'verbose_name_plural': 'Asset recovery procedures',
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='Criticality')),
                ('rto_hours', models.IntegerField(blank=True, help_text='Recovery Time Objective in hours', null=True, verbose_name='RTO (hours)')),
                ('rpo_hours', models.IntegerField(blank=True, help_text='Recovery Point Objective in hours', null=True, verbose_name='RPO (hours)')),
                ('mtpd_hours', models.IntegerField(blank=True, help_text='Maximum Tolerable Period of Disruption in hours', null=True, verbose_name='MTPD (hours)')),
                ('domain_impact_description', models.TextField(blank=True, help_text='How this service impacts its domain', null=True, verbose_name='Domain impact description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='draft', max_length=20, verbose_name='Status')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_services', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Business service',
                'verbose_name_plural': 'Business services',
            },
        ),
        migrations.CreateModel(
            name='ContinuityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('version', models.CharField(blank=True, default='1.0', max_length=50, verbose_name='Version')),
                ('scenario', models.TextField(blank=True, help_text='Disaster scenario this plan addresses', null=True, verbose_name='Scenario')),
                ('recovery_strategy', models.TextField(blank=True, null=True, verbose_name='Recovery strategy')),
                ('procedure_steps', models.TextField(blank=True, help_text='Step-by-step procedure (markdown)', null=True, verbose_name='Procedure steps')),
                ('responsible_team', models.TextField(blank=True, null=True, verbose_name='Responsible team')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='Last review date')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Next review date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('business_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_plans', to='business_continuity.businessservice', verbose_name='Business service')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('referenced_asset_procedures', models.ManyToManyField(blank=True, related_name='continuity_plans', to='business_continuity.assetrecoveryprocedure', verbose_name='Referenced asset procedures')),
            ],
            options={
                'verbose_name': 'Continuity plan',
                'verbose_name_plural': 'Continuity plans',
            },
        ),
        migrations.CreateModel(
            name='ContinuityPlanTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('test_date', models.DateField(verbose_name='Test date')),
                ('test_type', models.CharField(choices=[('tabletop', 'Tabletop'), ('walkthrough', 'Walkthrough'), ('simulation', 'Simulation'), ('full_recovery', 'Full recovery')], default='tabletop', max_length=20, verbose_name='Test type')),
                ('participants', models.TextField(blank=True, null=True, verbose_name='Participants')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='Objectives')),
                ('result', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure')], default='partial', max_length=20, verbose_name='Result')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Findings')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Actions')),
                ('continuity_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='business_continuity.continuityplan', verbose_name='Continuity plan')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuity_plan_tests', to='core.evidence', verbose_name='Evidence')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Continuity plan test',
                'verbose_name_plural': 'Continuity plan tests',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssetLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('dependency_type', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('supporting', 'Supporting')], default='important', max_length=20, verbose_name='Dependency type')),
                ('asset_impact_description', models.TextField(blank=True, help_text='How this asset impacts this service', null=True, verbose_name='Asset impact description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='core.asset', verbose_name='Asset')),
                ('business_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='business_continuity.businessservice', verbose_name='Business service')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Service-asset link',
                'verbose_name_plural': 'Service-asset links',
                'unique_together': {('business_service', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='businessservice',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='business_services', through='business_continuity.ServiceAssetLink', to='core.asset', verbose_name='Assets'),
        ),
    ]
